### PR TITLE
Remove element tests in individual demos and create a global test page - Fixes #43

### LINKED ISSUE #43: Separate demo for testing
#### In a new demo
- [ ] list all the buttons
- [ ] put buttons on top of multiple backgrounds (pink, dark, white)
- [ ] have each button coded using multiple elements (`a`, `input[type=submit]`, `input[type=button]`,  `button`)

#### In current demos
- [ ] consolidate variations (eg: remove "with anchors", "with buttons" in http://build.origami.ft.com/files/o-ft-buttons@1.7.1/demos/individual-standout.html)

### PR DESCRIPTION
**Pull request by kaelig**
Fixes #43

- Adds a test page with all button types
- Cleans up individual demos so that the style guide can use them without any dev tests in them

### CODE REVIEW

**Comment by kaelig** [comment]
Here's a look at the test page:

screencapture-localhost-8080-demos-local-test-html

**Comment by AlbertoElias** [comment]
Why not use o-ft-typography for the demo page? Would that be an overkill? obt supports adding dependencies just for demos via the build service

**Comment by triblondon** [comment]
It's a fine line between being realistic and being over complicated. If possible I think we should always have at least one demo that uses only the component being demoed.=

**Comment by AlbertoElias** [comment]
Oh, I meant for the test page

**Comment by kaelig** [comment]
Good point about using o-ft-typography in the demo. I'll keep that in mind in future iterations but maybe that's just creating yet another dependency as well.

**Pull request merged**
